site_name: Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Home:
        - Glossary: index.md
        - License: license.md
    - Overview:
        - F.A.Q.: faq.md
        - Developers: dev.md
        - Backend Services: backend.md
    - Mycroft:
        - Compatibility: compat.md
        - Comparison: mycroft.md

theme: readthedocs
