site_name: Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Home: index.md
    - Overview:
        - F.A.Q.: faq.md
        - Developers: dev.md
    - Mycroft:
        - Compatibility: compat.md
        - Comparison: mycroft.md

theme: readthedocs
