site_name: Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Home:
        - Introduction: index.md
        - Glossary: glossary.md
        - License: license.md
    - Overview:
        - F.A.Q.: faq.md
        - Developers: dev.md
        - Backend Services: backend.md
        - Configuration: config.md
    - Technologies:
        - OVOS-core: core.md
        - Platform/Hardware Abstraction Layer: PHAL.md
        - Plugin Manager: OPM.md
        - Shell: shell.md
        - Common Play: OCP.md
        - Config Assistant: OCA.md
    - Images:
        - Buildroot: buildroot.md
        - Manjaro: manjaro.md
    - Mycroft:
        - Compatibility: compat.md
        - Comparison: mycroft.md

theme: readthedocs
